---
# https://taskfile.dev
version: "3"

# vars:

tasks:
  default:
    deps: [setup]
    cmds:
      - task: trunk:format

  setup:
    silent: true
    desc: test that prerequisites are setup
    status:
      # - test "$(uname -s)" = "Darwin" # && echo "Darwin ok"
      - test $(command -v trunk)
      # - test $(command -v terraform) || brew install terraform
      # - test $(command -v checkov) || brew install checkov
      # - test $(command -v terraform-docs) || brew install terraform-docs
      # - test $(command -v jsonnet) || brew install go-jsonnet # includes jsonnetfmt
      # - test $(command -v jb) || brew install jsonnet-bundler

    cmds:
      # https://docs.trunk.io/getting-started#trunk-launcher
      # TODO Add trunk support in asdf-vm
      - echo "Installing Trunk Launcher ..."
      - echo "curl https://get.trunk.io -fsSL | bash"
      - curl https://get.trunk.io -fsSL | bash
      - echo "Please confirm the required commands and tools are available and try again." && exit 1

  docker:
    silent: true
    deps: [setup]
    desc: test that docker is running
    status:
      - pgrep -f Docker.app
    cmds:
      - open -a 'Docker'
      - echo "Waiting for Docker to start up ..."
      - sleep 20

  trunk:init:
    # silent: true
    desc: test that a trunk config file exists
    status:
      - test -f .trunk/trunk.yaml
    cmds:
      - trunk init
    generates:
      - ./.trunk/trunk.yaml

  trunk:format:
    silent: true
    desc: fix easy lint and style issues
    deps:
      - trunk:init
    cmds:
      - trunk fmt -a
